apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        # placeholder image; replace with your Docker Hub username and tag
        image: mgelvoleo/python-flask:initial
        ports:
        - containerPort: 5000

