name: CI/CD - Build (Docker Hub) and Deploy to kind (self-hosted)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.mgelvoleo }}/python-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images (latest + sha)
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Expose image name
        id: set-image
        run: |
          echo "image=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, linux, vm]
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Deploy to kind (update deployment image)
        run: |
          IMAGE=${{ needs.build-and-push.outputs.image }}
          echo "Updating deployment to use image: $IMAGE"
          kubectl set image deployment/python-deployment app=$IMAGE --namespace=default
          kubectl rollout status deployment/python-deployment --namespace=default --timeout=120s

